---
title: "Homework 2"
output: github_document
date: "2023-09-28"
---

```{r}
library(tidyverse)
```


## Problem 1

clean the data in pols-month.csv

```{r}
pols_df = 
  read_csv("data/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month","day")) |>
  mutate(
    month = case_match(
      month,
      "01" ~ "Jan",
      "02" ~ "Feb",
      "03" ~ "Mar",
      "04" ~ "Apr",
      "05" ~ "May",
      "06" ~ "Jun",
      "07" ~ "Jul",
      "08" ~ "Aug",
      "09" ~ "Sep",
      "10" ~ "Oct",
      "11" ~ "Nov",
      "12" ~ "Dec"
    ),
    year = as.numeric(year),
    prez_dem = replace(prez_dem,prez_dem == "1", "dem"),
    president = replace(prez_dem,prez_dem == "0", "gop")
    ) |>
  select( -prez_dem, -prez_gop, -day)

```

clean the data in snp.csv

```{r}
snp_df = 
  read_csv("data/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day","year")) |>
  mutate(
    year = as.numeric(year),
    year = ifelse( year <= 15, year + 2000, year + 1900),
    month = as.numeric(month)
  ) |>
  arrange(year, month) |>
  mutate(
    month = as.character(month),
    month = case_match(
      month,
      "1" ~ "Jan",
      "2" ~ "Feb",
      "3" ~ "Mar",
      "4" ~ "Apr",
      "5" ~ "May",
      "6" ~ "Jun",
      "7" ~ "Jul",
      "8" ~ "Aug",
      "9" ~ "Sep",
      "10" ~ "Oct",
      "11" ~ "Nov",
      "12" ~ "Dec"
    ),
  ) |>
  select(year, month, close) 

```

tidy the unemployment data

```{r}
unemployment_df = 
  read_csv("data/unemployment.csv") |>
  pivot_longer(
    Jan:Dec,
    names_to = "month", 
    values_to = "percentage") |>
  janitor::clean_names()

```

join the datasets

```{r}
combine_df = 
  full_join(snp_df,pols_df)
combine_df = 
  full_join(combine_df, unemployment_df)
```









